"""
county_policy_model.py

Enacted-restriction model on the county aggregate layer. Reads
data/county_aggregate.csv (produced by county_aggregator.py, which QC-gates
all inputs), fits and validates a regularized logistic model, and writes:

  - data/county_policy_metrics.json   (full validation metrics)
  - data/county_policy_scores.csv     (per-county cross-validated score,
                                       map-consumable)
  - data/county_policy_report.md      (auto-generated report; the report is
                                       produced by the model, not by hand)

Outcome: has_enacted_restrictive. A county has at least one enacted
restrictive policy (moratorium or zoning restriction with terminal enacted
status). Chosen because an enacted ordinance is a public record: the label
does not depend on press coverage the way opposition presence does.

Validation stack:
  - Repeated stratified k-fold (5 folds x 5 repeats, fixed seeds).
  - AUC and Brier reported as p10/p50/p90 across the 25 folds.
  - Calibration slope and intercept fit on pooled out-of-fold predictions
    (logistic recalibration); a well-calibrated model has slope near 1 and
    intercept near 0.
  - Coefficient stability: per-variable min/median/max across all fold fits.
    A variable whose coefficient changes sign across folds is flagged
    unstable and reported as such.
  - Per-county scores are out-of-fold (never scored by a model that saw the
    county in training).

Reporting rules: variable trust tiers accompany every table; associations
are predictive, not causal; no figure is a probability that a new project
draws opposition; leak audit runs on all generated outputs; no em-dashes.

Usage: python county_policy_model.py
"""

from __future__ import annotations

import argparse
import csv
import datetime as dt
import hashlib
import json
import math
import os
import re
import statistics as st
import sys

ROOT = os.path.dirname(os.path.abspath(__file__))


def P(*parts):
    return os.path.join(ROOT, *parts)


AGG_CSV = P("data", "county_aggregate.csv")
MANIFEST = P("data", "county_aggregate_manifest.json")
OUT_METRICS = P("data", "county_policy_metrics.json")
OUT_SCORES = P("data", "county_policy_scores.csv")
OUT_MD = P("data", "county_policy_report.md")

N_SPLITS = 5
N_REPEATS = 5
SEED = 7

# Specification selection, re-registered 2026-08-26.
#
# Tier 3 variables are strongly collinear (density x population +0.87,
# income x education +0.69, margin loads on all urbanicity variables), which
# makes coefficients sign-unstable under weak regularization. A variable
# whose coefficient changes sign across folds is not telling us a direction,
# and shipping it would put a number in a client artifact whose sign is
# noise. So sign stability, not accuracy, is the admission rule.
#
# What changed and why. The previous design froze a hand-written list of
# five variable subsets and required the shipped model to score within
# AUC_TOLERANCE of the best point in that frozen grid. That rule is
# self-defeating: on 2026-08-26 a subset scored 0.8074 while sign-unstable,
# which lifted the tolerance floor above every sign-stable point in the
# grid, and the module refused to ship anything at all. The frozen list
# could not express the stable variant of the winning subset, so no amount
# of re-running would have recovered it, and widening C_GRID was tested and
# did not either.
#
# What is registered now is the RULE, not the list of variables. The
# variable set is derived from the data on every run by a deterministic
# procedure, so a variable enters the model when it earns its place and
# leaves when it stops earning it, and every such change is written to
# data/county_model_spec_history.csv with the coefficient evidence behind
# it. The rule:
#
#   1. Candidates are generated by backward elimination from the full
#      variable pool, at each regularization strength: fit, and while the
#      fit is sign-unstable drop the single least trustworthy variable and
#      refit. "Least trustworthy" is defined below and is a property of the
#      coefficient distribution, never of the accuracy, so the elimination
#      path cannot be steered toward a better score.
#   2. The legacy named subsets are evaluated too, as anchors, so the
#      history stays comparable and a hand-registered subset can still win.
#   3. Admissible: every coefficient sign-stable across all 25 folds.
#   4. Among admissible: highest median AUC, then most variables retained,
#      then strongest regularization.
#   5. The accuracy given up for stability is reported as stability_cost
#      (best overall minus best admissible) rather than used as a veto.
#      Under a frozen list a veto was the only safe response to a gap;
#      under an active search the gap is a measured property of the data
#      and the honest response is to ship the best trustworthy model and
#      state what it cost. A gap beyond STABILITY_COST_ALARM is still a
#      hard stop, because at that point the trustworthy model is not
#      describing the same phenomenon.
#
# Promotion is unaffected: calibration_gate.py still governs whether any of
# this reaches a client surface.
C_GRID = (1.0, 0.3, 0.1, 0.03, 0.01)
AUC_TOLERANCE = 0.01
STABILITY_COST_ALARM = 0.05
SPEC_HISTORY = P("data", "county_model_spec_history.csv")
MIN_VARS = 3          # never eliminate below a describable model
SPECS = {
    "full": ["margin_2024", "margin_shift", "existing_dc_count",
             "n_projects_tracked", "state_legislation_events", "land_sqmi",
             "median_hh_income", "pop_density_sqmi", "pct_bachelors_plus",
             "population"],
    "no_shift": ["margin_2024", "existing_dc_count", "n_projects_tracked",
                 "state_legislation_events", "land_sqmi",
                 "median_hh_income", "pop_density_sqmi",
                 "pct_bachelors_plus", "population"],
    "drop_density": ["margin_2024", "margin_shift", "existing_dc_count",
                     "n_projects_tracked", "state_legislation_events",
                     "land_sqmi", "median_hh_income", "pct_bachelors_plus",
                     "population"],
    "core_six": ["margin_2024", "existing_dc_count", "median_hh_income",
                 "pop_density_sqmi", "pct_bachelors_plus", "population"],
    "tier1_plus_size": ["margin_2024", "existing_dc_count",
                        "n_projects_tracked", "land_sqmi", "population"],
}

# (column, report label, trust tier, transform)
# Tier 1: low detection-bias exposure. Tier 3: variable also predicts news
# coverage; on this outcome (public-record ordinances) exposure is reduced
# but tiering is still reported.
VARS = [
    ("margin_2024", "2024 presidential margin (positive = Democratic)", 1, "identity"),
    ("margin_shift", "margin shift 2016 to 2024 (positive = moved Democratic)", 1, "identity"),
    ("existing_dc_count", "existing data centers (atlas)", 1, "log1p"),
    ("n_projects_tracked", "tracked data center projects", 1, "log1p"),
    ("state_legislation_events", "state-level legislation activity (state-inherited)", 2, "log1p"),
    ("land_sqmi", "county land area", 1, "log1p"),
    ("median_hh_income", "median household income", 3, "log10"),
    ("pop_density_sqmi", "population density", 3, "log1p"),
    ("pct_bachelors_plus", "bachelors degree or higher, pct", 3, "identity"),
    ("population", "population", 3, "log1p"),
]

# margin_shift is derived at load time from margin_2024 - margin_2016.
# state_legislation_events is built exclusively from state-scope records
# with no county, which cannot contribute to the county outcome; it is
# leakage-free by construction and tiered 2 (state-inherited, shared by
# every county in a state).


# --------------------------------------------------------------------------
# Selection primitives. Pure functions over coefficient distributions, so the
# rule can be self-tested without fitting anything.
# --------------------------------------------------------------------------

def is_sign_stable(coefs) -> bool:
    """True when every fold agreed on the direction of this variable."""
    cs = list(coefs)
    return bool(cs) and (min(cs) > 0 or max(cs) < 0)


def spec_is_stable(coef_folds: dict) -> bool:
    return all(is_sign_stable(cs) for cs in coef_folds.values())


def instability(coefs) -> float:
    """How evenly a variable's coefficient straddles zero, 0.0 to 1.0.

    0.0 means every fold agreed on the sign. 1.0 means the excursions either
    side of zero are the same size, which is a variable contributing a
    direction it cannot hold. Deliberately a function of the coefficient
    distribution alone: accuracy is not an input, so the elimination path
    cannot be steered toward a better score.
    """
    cs = list(coefs)
    if not cs or is_sign_stable(cs):
        return 0.0
    lo, hi = abs(min(cs)), abs(max(cs))
    if max(lo, hi) == 0:
        return 1.0
    return min(lo, hi) / max(lo, hi)


def least_trustworthy(coef_folds: dict) -> str | None:
    """The variable to eliminate next, or None if all are sign-stable.

    Most evenly straddling zero first; ties broken by the smaller median
    magnitude, so between two equally undecided variables the one
    contributing least is dropped. Both keys are deterministic and the final
    tiebreak is the variable name, so the path does not depend on dict order.
    """
    unstable = {f: cs for f, cs in coef_folds.items() if not is_sign_stable(cs)}
    if not unstable:
        return None
    return min(unstable,
               key=lambda f: (-instability(unstable[f]),
                              abs(st.median(unstable[f])), f))


def choose_admissible(grid: list) -> dict | None:
    """Highest median AUC, then most variables retained, then strongest
    regularization. Applied only to sign-stable candidates."""
    admissible = [g for g in grid if g["sign_stable"]]
    if not admissible:
        return None
    return sorted(admissible,
                  key=lambda g: (-g["auc_median"], -g["n_vars"], g["C"],
                                 g["spec"]))[0]


def stability_cost(grid: list, chosen: dict) -> float:
    """Median AUC given up by requiring sign stability."""
    if not grid:
        return 0.0
    return round(max(g["auc_median"] for g in grid) - chosen["auc_median"], 4)


def spec_diff(previous: list, current: list) -> tuple[list, list]:
    """(entered, left) between two variable sets, both sorted."""
    prev, cur = set(previous or []), set(current or [])
    return sorted(cur - prev), sorted(prev - cur)


def explain_drop(var: str, coefs) -> str:
    """Why a variable left the model, in the evidence that removed it."""
    if coefs is None:
        return f"{var}: not present in the selected specification this run"
    cs = list(coefs)
    if not cs:
        return f"{var}: no coefficient recorded"
    if is_sign_stable(cs):
        return (f"{var}: sign stable but not selected; another specification "
                f"scored higher under the registered criterion")
    return (f"{var}: coefficient changed sign across folds, ranging "
            f"{min(cs):+.4f} to {max(cs):+.4f}, so its direction is not "
            f"supported by the data")


def explain_add(var: str, coefs) -> str:
    """Why a variable entered the model."""
    cs = list(coefs or [])
    if not cs:
        return f"{var}: entered the selected specification"
    direction = "positive" if st.median(cs) > 0 else "negative"
    return (f"{var}: sign stable this run, {direction} in all folds, median "
            f"coefficient {st.median(cs):+.4f}")


HISTORY_FIELDS = ["run_date", "n_counties", "n_positive", "base_rate",
                  "spec", "C", "n_vars", "variables", "entered", "left",
                  "auc_median", "stability_cost", "reasons", "inputs_hash"]


def read_spec_history(path: str = None) -> list:
    """Every recorded specification change, oldest first."""
    try:
        with open(path or SPEC_HISTORY, encoding="utf-8-sig", newline="") as fh:
            return list(csv.DictReader(fh))
    except OSError:
        return []


def append_spec_history(row: dict, path: str = None) -> None:
    """Append-only. One row per change, never per run: a file that grows by a
    row a day whether or not anything moved is a log, not a history, and
    nobody reads it."""
    target = path or SPEC_HISTORY
    os.makedirs(os.path.dirname(target), exist_ok=True)
    exists = os.path.exists(target)
    with open(target, "a", encoding="utf-8", newline="") as fh:
        w = csv.DictWriter(fh, fieldnames=HISTORY_FIELDS, lineterminator="\n")
        if not exists:
            w.writeheader()
        w.writerow({k: row.get(k, "") for k in HISTORY_FIELDS})


def dropped_evidence(grid: list, results: dict, var: str):
    """The coefficient folds that explain why a variable is not in the
    selected specification.

    Taken from the widest candidate that still contained it, which is where
    its instability is visible. A variable dropped by elimination shows the
    fit that decided to drop it; one merely not selected shows its last
    stable behaviour, and explain_drop says which case it is.
    """
    holders = [g for g in grid if var in g.get("variables", [])]
    if not holders:
        return None
    widest = max(holders, key=lambda g: (g["n_vars"], -g["C"]))
    res = results.get((widest["spec"], widest["C"]))
    return (res or {}).get("coef_folds", {}).get(var)


def input_hash() -> str:
    """Short hash of the aggregate manifest, so a specification change can be
    traced to the data change that caused it."""
    try:
        with open(MANIFEST, encoding="utf-8") as fh:
            payload = json.load(fh).get("inputs", {})
        return hashlib.sha1(
            json.dumps(payload, sort_keys=True).encode("utf-8")
        ).hexdigest()[:12]
    except (OSError, ValueError):
        return ""


def parse_float(v):
    try:
        return float(v)
    except (TypeError, ValueError):
        return None


def transform(name, x):
    if x is None:
        return None
    if name == "log1p":
        return math.log1p(max(x, 0.0))
    if name == "log10":
        return math.log10(x) if x > 0 else None
    return x


def load():
    rows = list(csv.DictReader(open(AGG_CSV, encoding="utf-8-sig")))
    if not rows:
        print("ERROR: empty aggregate; run county_aggregator.py first",
              file=sys.stderr)
        sys.exit(1)
    # Exclude Puerto Rico municipios from the modeling frame: no
    # presidential margin exists, income sits far outside the mainland
    # distribution, and local land-use institutions differ. They remain in
    # the aggregate layer for the map.
    kept = [r for r in rows if not r["fips"].startswith("72")]
    for r in kept:
        m24, m16 = parse_float(r.get("margin_2024")), parse_float(r.get("margin_2016"))
        r["margin_shift"] = ("" if m24 is None or m16 is None
                             else m24 - m16)
    return kept, len(rows) - len(kept)


def main() -> int:
    try:
        import numpy as np
        from sklearn.impute import SimpleImputer
        from sklearn.linear_model import LogisticRegression
        from sklearn.metrics import brier_score_loss, roc_auc_score
        from sklearn.model_selection import RepeatedStratifiedKFold
        from sklearn.pipeline import make_pipeline
        from sklearn.preprocessing import StandardScaler
    except ImportError:
        print("ERROR: scikit-learn required", file=sys.stderr)
        return 1

    rows, n_excluded_pr = load()
    all_feats = [v for v, _, _, _ in VARS]
    tr_by = {v: tr for v, _, _, tr in VARS}
    Xall = np.array(
        [[np.nan if (t := transform(tr, parse_float(r[f]))) is None else t
          for f, _, _, tr in VARS] for r in rows], dtype=float)
    y = np.array([int(r["has_enacted_restrictive"]) for r in rows])
    fips = [r["fips"] for r in rows]
    cv = RepeatedStratifiedKFold(n_splits=N_SPLITS, n_repeats=N_REPEATS,
                                 random_state=SEED)

    def run_cv(feat_list, c_reg):
        ix = [all_feats.index(f) for f in feat_list]
        X = Xall[:, ix]
        aucs, briers = [], []
        coef_folds = {f: [] for f in feat_list}
        oof_sum = np.zeros(len(y))
        oof_cnt = np.zeros(len(y))
        for tr_ix, te_ix in cv.split(X, y):
            pipe = make_pipeline(
                SimpleImputer(strategy="median"),
                StandardScaler(),
                LogisticRegression(C=c_reg, max_iter=4000))
            pipe.fit(X[tr_ix], y[tr_ix])
            p = pipe.predict_proba(X[te_ix])[:, 1]
            aucs.append(roc_auc_score(y[te_ix], p))
            briers.append(brier_score_loss(y[te_ix], p))
            for f, c in zip(feat_list,
                            pipe.named_steps["logisticregression"].coef_[0]):
                coef_folds[f].append(float(c))
            oof_sum[te_ix] += p
            oof_cnt[te_ix] += 1
        stable = all(min(cs) > 0 or max(cs) < 0
                     for cs in coef_folds.values())
        return {"aucs": aucs, "briers": briers, "coef_folds": coef_folds,
                "oof": oof_sum / oof_cnt, "sign_stable": stable}

    # --- candidate search: named anchors plus backward elimination ---
    # The anchors keep the history comparable with the frozen-grid era. The
    # elimination paths are what let a variable leave the model when it stops
    # holding a direction, and rejoin it when it starts holding one again:
    # every path restarts from the full pool on every run, so nothing is
    # permanently excluded by a past run's data.
    grid = []
    results = {}
    feature_sets = {}
    seen = set()

    def evaluate(label, flist, c_reg):
        key = (tuple(sorted(flist)), c_reg)
        if key in seen:
            return None
        seen.add(key)
        res = run_cv(flist, c_reg)
        results[(label, c_reg)] = res
        feature_sets[(label, c_reg)] = list(flist)
        entry = {"spec": label, "C": c_reg, "n_vars": len(flist),
                 "auc_median": round(st.median(res["aucs"]), 4),
                 "sign_stable": res["sign_stable"],
                 "variables": list(flist)}
        grid.append(entry)
        return res

    # Elimination runs from the full pool AND from each registered anchor.
    # Starting only from the full pool made the search greedy in one
    # direction: it can only remove variables that fail the stability rule,
    # so a stable variable that happens to depress accuracy is never
    # reconsidered, and the better stable specification sitting one anchor
    # away is never reached. Starting from every pre-registered anchor fixes
    # that without ever dropping a variable for being inconvenient, which is
    # the line this rule exists to hold.
    starts = [("full_pool", list(all_feats))] + [
        (name, list(flist)) for name, flist in SPECS.items()]

    for c_reg in C_GRID:
        for origin, start in starts:
            working = list(start)
            step = 0
            while len(working) >= MIN_VARS:
                label = origin if step == 0 else f"{origin}_minus{step}"
                res = evaluate(label, working, c_reg)
                if res is None:                 # this set already evaluated
                    res = run_cv(working, c_reg)
                if res["sign_stable"]:
                    break
                drop = least_trustworthy(res["coef_folds"])
                if drop is None:
                    break
                working = [f for f in working if f != drop]
                step += 1

    sel = choose_admissible(grid)
    if sel is None:
        print("ERROR: no sign-stable specification exists at any "
              "regularization strength, including the minimum variable set; "
              "the county layer cannot ship coefficients this run",
              file=sys.stderr)
        return 1
    cost = stability_cost(grid, sel)
    if cost > STABILITY_COST_ALARM:
        print(f"ERROR: the best sign-stable specification gives up "
              f"{cost:.4f} AUC against the best specification overall, "
              f"beyond the registered alarm of {STABILITY_COST_ALARM}. The "
              f"trustworthy model is no longer describing the same "
              f"phenomenon; this needs a look before anything ships.",
              file=sys.stderr)
        return 1
    feats = feature_sets[(sel["spec"], sel["C"])]
    C_REG = sel["C"]
    chosen = results[(sel["spec"], sel["C"])]
    aucs, briers = chosen["aucs"], chosen["briers"]
    coef_folds = chosen["coef_folds"]
    oof = chosen["oof"]

    # calibration: logistic recalibration on pooled out-of-fold predictions.
    # Under strong shrinkage the raw scores are compressed (underconfident),
    # so a recalibration layer is part of the model. To keep the reported
    # calibration honest, recalibrated scores are cross-fitted: each
    # county's calibrated score comes from a recalibration model fit on
    # folds that exclude it.
    eps = 1e-6
    logit_oof = np.log(np.clip(oof, eps, 1 - eps) /
                       np.clip(1 - oof, eps, 1 - eps)).reshape(-1, 1)
    recal = LogisticRegression(C=1e6, max_iter=4000).fit(logit_oof, y)
    cal_slope = float(recal.coef_[0][0])
    cal_intercept = float(recal.intercept_[0])

    from sklearn.model_selection import StratifiedKFold
    oof_cal = np.zeros(len(y))
    for tr_ix, te_ix in StratifiedKFold(n_splits=5, shuffle=True,
                                        random_state=SEED).split(logit_oof, y):
        rc = LogisticRegression(C=1e6, max_iter=4000)
        rc.fit(logit_oof[tr_ix], y[tr_ix])
        oof_cal[te_ix] = rc.predict_proba(logit_oof[te_ix])[:, 1]
    logit_cal = np.log(np.clip(oof_cal, eps, 1 - eps) /
                       np.clip(1 - oof_cal, eps, 1 - eps)).reshape(-1, 1)
    post = LogisticRegression(C=1e6, max_iter=4000).fit(logit_cal, y)
    post_slope = float(post.coef_[0][0])
    post_intercept = float(post.intercept_[0])
    brier_cal = float(np.mean((oof_cal - y) ** 2))

    def pctile(v, q):
        s = sorted(v)
        return s[min(len(s) - 1, int(q * len(s)))]

    # --- specification history: what changed, and the evidence for it ---
    previous = read_spec_history()
    prior_vars = previous[-1]["variables"].split("; ") if previous else []
    entered, left = spec_diff(prior_vars, sorted(feats))
    reasons = ([explain_add(v, coef_folds.get(v)) for v in entered]
               + [explain_drop(v, dropped_evidence(grid, results, v))
                  for v in left])
    changed = bool(entered or left) or not previous
    if changed:
        append_spec_history({
            "run_date": dt.date.today().isoformat(),
            "n_counties": int(len(y)),
            "n_positive": int(y.sum()),
            "base_rate": round(float(y.mean()), 4),
            "spec": sel["spec"],
            "C": C_REG,
            "n_vars": len(feats),
            "variables": "; ".join(sorted(feats)),
            "entered": "; ".join(entered),
            "left": "; ".join(left),
            "auc_median": round(st.median(aucs), 4),
            "stability_cost": cost,
            "reasons": " | ".join(reasons) if reasons
                       else "first recorded specification",
            "inputs_hash": input_hash(),
        })

    base = float(y.mean())
    metrics = {
        "n": int(len(y)),
        "n_excluded_puerto_rico": int(n_excluded_pr),
        "n_positive": int(y.sum()),
        "base_rate": round(base, 4),
        "cv": {"folds": N_SPLITS, "repeats": N_REPEATS, "seed": SEED},
        "specification_selection": {
            "criterion": "sign-stable on all folds; among those, highest "
                         "median AUC, then most variables retained, then "
                         "strongest regularization. Candidates are the named "
                         "anchors plus backward elimination from the full "
                         "variable pool, regenerated from the data on every "
                         "run, so a variable enters when it holds a "
                         "direction and leaves when it stops.",
            "registered": "2026-08-26",
            "selected": {"spec": sel["spec"], "C": C_REG,
                         "variables": feats},
            "stability_cost": cost,
            "stability_cost_note": (
                "median AUC given up by requiring every coefficient to hold "
                "its sign across all folds. Reported, not used as a veto; a "
                "gap beyond " + str(STABILITY_COST_ALARM) + " is a hard "
                "stop."),
            "stability_cost_alarm": STABILITY_COST_ALARM,
            "changed_this_run": changed,
            "entered": entered,
            "left": left,
            "change_reasons": reasons,
            "grid": grid},
        "roc_auc": {"p10": round(pctile(aucs, .10), 4),
                    "p50": round(st.median(aucs), 4),
                    "p90": round(pctile(aucs, .90), 4)},
        "brier": {"p10": round(pctile(briers, .10), 4),
                  "p50": round(st.median(briers), 4),
                  "p90": round(pctile(briers, .90), 4),
                  "base_rate_brier": round(base * (1 - base), 4)},
        "calibration": {
            "raw_slope": round(cal_slope, 3),
            "raw_intercept": round(cal_intercept, 3),
            "post_recalibration_slope": round(post_slope, 3),
            "post_recalibration_intercept": round(post_intercept, 3),
            "brier_calibrated": round(brier_cal, 4),
            "note": "raw scores are compressed by shrinkage; the model "
                    "includes a cross-fitted logistic recalibration layer. "
                    "calibrated_score in the scores file is cross-fitted: "
                    "no county's calibration was fit on itself. Post "
                    "slope near 1 and intercept near 0 indicate the "
                    "calibrated scores are honest probabilities."},
        "coefficients": {
            f: {"min": round(min(cs), 3), "median": round(st.median(cs), 3),
                "max": round(max(cs), 3),
                "sign_stable": bool(min(cs) > 0) or bool(max(cs) < 0)}
            for f, cs in coef_folds.items()},
        "aggregate_manifest": (json.load(open(MANIFEST))
                               if os.path.exists(MANIFEST) else None),
    }
    with open(OUT_METRICS, "w", encoding="utf-8") as fh:
        json.dump(metrics, fh, indent=2)

    # per-county out-of-fold scores (map layer)
    dec = np.searchsorted(np.quantile(oof_cal, np.linspace(.1, .9, 9)),
                          oof_cal) + 1
    with open(OUT_SCORES, "w", newline="", encoding="utf-8") as fh:
        w = csv.writer(fh, lineterminator="\n")
        w.writerow(["fips", "raw_oof_score", "calibrated_score",
                    "score_decile", "has_enacted_restrictive"])
        for i in range(len(y)):
            w.writerow([fips[i], round(float(oof[i]), 4),
                        round(float(oof_cal[i]), 4), int(dec[i]),
                        int(y[i])])

    # auto-generated report
    L = []
    w = L.append
    w("# County Enacted-Restriction Model")
    w("")
    w("Auto-generated by county_policy_model.py. Do not edit by hand; rerun "
      "the module after data updates. Companion files: "
      "county_policy_metrics.json, county_policy_scores.csv.")
    w("")
    w("**Internal diagnostic. Associations are predictive, not causal. "
      "Scores are out-of-fold cross-validated probabilities of the county "
      "having an enacted restrictive policy given its profile; they are not "
      "probabilities that a new project draws opposition.**")
    w("")
    w("## Outcome and frame")
    w("")
    w(f"- Frame: {metrics['n']} counties. Puerto Rico municipios "
      f"(n = {n_excluded_pr}) are excluded from the model and retained in "
      f"the aggregate layer: no presidential margin exists and land-use "
      f"institutions differ.")
    w(f"- Positive: county has at least one enacted restrictive policy, "
      f"n = {metrics['n_positive']} "
      f"(base rate {100 * base:.1f} pct).")
    w("- The outcome is an enacted public record, which reduces but does "
      "not remove detection-bias exposure relative to opposition-presence "
      "outcomes.")
    w("")
    w("## Validation")
    w("")
    a, b = metrics["roc_auc"], metrics["brier"]
    w(f"- Repeated stratified CV ({N_SPLITS} folds x {N_REPEATS} repeats, "
      f"seed {SEED}).")
    w(f"- Specification selected by fixed criterion (see metrics JSON for "
      f"the full grid): spec '{sel['spec']}' with C = {C_REG}. Tier 3 "
      f"variables are strongly collinear (density x population +0.87, "
      f"income x education +0.69), so sign stability requires shrinkage; "
      f"only sign-stable specifications within {AUC_TOLERANCE} AUC of the "
      f"grid best are admissible, and among those the criterion retains "
      f"as many variables as possible. Under strong shrinkage, coefficient "
      f"magnitudes are compressed toward zero by design; read relative "
      f"ordering and sign, not absolute size.")
    w(f"- ROC AUC: {a['p50']:.2f} (p10 {a['p10']:.2f}, p90 {a['p90']:.2f}).")
    w(f"- Brier: {b['p50']:.3f} vs base-rate Brier "
      f"{b['base_rate_brier']:.3f}.")
    c = metrics["calibration"]
    w(f"- Raw-score calibration slope {c['raw_slope']:.2f} (shrinkage "
      f"compresses raw scores); the model therefore includes a "
      f"cross-fitted recalibration layer. Post-recalibration slope "
      f"{c['post_recalibration_slope']:.2f}, intercept "
      f"{c['post_recalibration_intercept']:.2f}. Use calibrated_score "
      f"from the scores file.")
    w("")
    w("## Coefficients (fold stability)")
    w("")
    w("| Variable | Tier | Median | Fold range | Sign stable |")
    w("|---|---|---|---|---|")
    tier = {v: t for v, _, t, _ in VARS}
    label = {v: l for v, l, _, _ in VARS}
    for f, cs in sorted(metrics["coefficients"].items(),
                        key=lambda kv: -abs(kv[1]["median"])):
        w(f"| {label[f]} | {tier[f]} | {cs['median']:+.2f} | "
          f"{cs['min']:+.2f} to {cs['max']:+.2f} | "
          f"{'yes' if cs['sign_stable'] else 'NO'} |")
    w("")
    w("Coefficients are on standardized, transformed inputs (logs on "
      "density, population, DC count, income). Variables whose coefficient "
      "changes sign across folds should not be interpreted directionally.")
    w("")
    w("## Trust tiers")
    w("")
    w("- Tier 1: political margin, existing DC count. Low detection-bias "
      "exposure; safest for external use.")
    w("- Tier 3: population, density, income, education. These variables "
      "also predict news coverage; on this public-record outcome the "
      "exposure is reduced, and it is still reported.")
    w("")
    w("## Standing caveats")
    w("")
    w("- Scores are out-of-fold: no county is scored by a model that saw "
      "it in training.")
    w("- The score is a resemblance measure over county profiles, "
      "calibrated to the observed enactment base rate. It is not a "
      "forecast of opposition to any specific project.")
    w("- Inputs are QC-gated upstream by county_aggregator.py; the input "
      "manifest is embedded in county_policy_metrics.json for "
      "reproducibility.")
    w("")

    with open(OUT_MD, "w", encoding="utf-8") as fh:
        fh.write("\n".join(L) + "\n")

    # leak audit over all generated outputs
    pat = re.compile(r"\b(win|wins|loss|losses|lost)\b", re.I)
    leaks = []
    for path in (OUT_METRICS, OUT_SCORES, OUT_MD):
        for i, line in enumerate(open(path, encoding="utf-8"), 1):
            if pat.search(line):
                leaks.append(f"{os.path.basename(path)}:{i}")

    print(f"n={metrics['n']} ({metrics['n_positive']} enacted) | "
          f"AUC {a['p50']:.2f} [{a['p10']:.2f}-{a['p90']:.2f}] | "
          f"Brier {b['p50']:.3f} (base {b['base_rate_brier']:.3f}) | "
          f"post-recal slope {c['post_recalibration_slope']:.2f}")
    unstable = [f for f, cs in metrics["coefficients"].items()
                if not cs["sign_stable"]]
    if unstable:
        print("sign-unstable coefficients:", ", ".join(unstable))
    print("wrote metrics, scores, report")
    print("leak audit:", "FAIL " + ", ".join(leaks) if leaks else "clean")
    return 1 if leaks else 0


# --------------------------------------------------------------------------
# selftest
# --------------------------------------------------------------------------

def selftest() -> int:
    """Covers the selection rule, which is the part that decides what ships.

    Deliberately fits nothing: every function under test operates on
    coefficient distributions, so the rule can be checked exactly and in a
    second, without scikit-learn and without the aggregate layer.
    """
    import tempfile
    checks = []

    def check(name, ok):
        checks.append((name, bool(ok)))

    check("all-positive folds are stable", is_sign_stable([0.2, 0.9, 0.4]))
    check("all-negative folds are stable", is_sign_stable([-0.2, -0.9]))
    check("a sign change is not stable", not is_sign_stable([-0.1, 0.3]))
    check("a zero coefficient is not stable", not is_sign_stable([0.0, 0.3]))
    check("no folds is not stable", not is_sign_stable([]))

    check("a stable variable has no instability",
          instability([0.2, 0.9]) == 0.0)
    check("an evenly straddling variable is maximally unstable",
          instability([-0.5, 0.5]) == 1.0)
    check("a barely straddling variable is nearly trustworthy",
          instability([-0.01, 0.9]) < 0.05)
    check("instability ignores magnitude",
          instability([-1.0, 2.0]) == instability([-10.0, 20.0]))

    folds = {"steady": [0.5, 0.6], "wobble": [-0.4, 0.45],
             "nudge": [-0.01, 0.9]}
    check("the most evenly straddling variable goes first",
          least_trustworthy(folds) == "wobble")
    check("a fully stable set eliminates nothing",
          least_trustworthy({"a": [0.1, 0.2]}) is None)
    # Both straddle zero just as evenly, so the tie falls to magnitude and
    # the one contributing less is the one that goes.
    tie = {"big": [-0.5, 0.5, 0.5], "small": [-0.05, 0.05, 0.05]}
    check("equally unstable variables break the tie on magnitude",
          least_trustworthy(tie) == "small")

    grid = [
        {"spec": "unstable_leader", "C": 1.0, "n_vars": 9,
         "auc_median": 0.8074, "sign_stable": False},
        {"spec": "stable_best", "C": 0.1, "n_vars": 7,
         "auc_median": 0.8076, "sign_stable": True},
        {"spec": "stable_smaller", "C": 0.1, "n_vars": 5,
         "auc_median": 0.8076, "sign_stable": True},
        {"spec": "stable_weak", "C": 1.0, "n_vars": 5,
         "auc_median": 0.7944, "sign_stable": True},
    ]
    sel = choose_admissible(grid)
    check("an unstable specification never wins however accurate",
          sel["spec"] != "unstable_leader")
    check("the most accurate stable specification wins",
          sel["auc_median"] == 0.8076)
    check("a tie on accuracy keeps more variables",
          sel["spec"] == "stable_best")
    check("no stable candidate yields no selection",
          choose_admissible([g for g in grid if not g["sign_stable"]]) is None)

    check("stability cost is measured against the whole grid",
          stability_cost(grid, sel) == round(0.8076 - 0.8076, 4))
    check("a stable leader costs nothing",
          stability_cost(grid, grid[1]) == 0.0)
    check("cost is positive when stability loses accuracy",
          stability_cost([grid[0], grid[3]], grid[3]) == 0.013)

    entered, left = spec_diff(["a", "b", "c"], ["b", "c", "d"])
    check("entering variables are detected", entered == ["d"])
    check("leaving variables are detected", left == ["a"])
    check("a first run enters everything",
          spec_diff([], ["a", "b"]) == (["a", "b"], []))
    check("an unchanged specification diffs to nothing",
          spec_diff(["a"], ["a"]) == ([], []))

    # A variable can leave and later rejoin: every run restarts from the full
    # pool, so exclusion is never permanent. This is the property that makes
    # the model adaptive rather than merely shrinking.
    rejoin_in, rejoin_out = spec_diff(["a", "b"], ["a", "b", "c"])
    check("a previously dropped variable can rejoin", rejoin_in == ["c"])

    reason = explain_drop("margin_2024", [-0.112, 0.1263])
    check("a drop reason carries the coefficient range",
          "-0.1120" in reason and "+0.1263" in reason)
    check("a drop reason names the direction problem",
          "direction is not supported" in reason)
    check("a stable-but-unselected variable says so",
          "not selected" in explain_drop("x", [0.4, 0.5]))
    check("an add reason carries the direction",
          "positive" in explain_add("n_projects_tracked", [0.7, 0.8]))
    check("a negative add reason says negative",
          "negative" in explain_add("existing_dc_count", [-0.6, -0.5]))

    with tempfile.TemporaryDirectory() as tmp:
        hist = os.path.join(tmp, "data", "hist.csv")
        check("an absent history reads as empty", read_spec_history(hist) == [])
        append_spec_history({"run_date": "2026-08-26", "spec": "a",
                             "variables": "x; y", "entered": "x; y",
                             "reasons": "first recorded specification"}, hist)
        append_spec_history({"run_date": "2026-09-02", "spec": "b",
                             "variables": "x", "left": "y",
                             "reasons": "y: coefficient changed sign"}, hist)
        rows = read_spec_history(hist)
        check("history is append-only and ordered", len(rows) == 2
              and rows[0]["run_date"] == "2026-08-26")
        check("the header is written once",
              sum(1 for line in open(hist) if line.startswith("run_date")) == 1)
        check("the latest row carries the current variables",
              rows[-1]["variables"] == "x")
        check("every field is present on every row",
              all(set(r) == set(HISTORY_FIELDS) for r in rows))

    failed = [n for n, ok in checks if not ok]
    for n, ok in checks:
        print(f"  {'PASS' if ok else 'FAIL'}  {n}")
    print(f"\n{len(checks) - len(failed)}/{len(checks)} checks passed")
    return 1 if failed else 0


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--selftest", action="store_true")
    raise SystemExit(selftest() if ap.parse_args().selftest else main())
