"""
feature_asymmetry_check.py

Robustness check for the days_to_first_opposition feature in the outcome
model. Verifies that the association between opposition-arrival speed and
blocking is not an artifact of asymmetric date quality across outcome arms.

Checks, by arm (blocked_confirmed vs not blocked):
  1. Coverage symmetry: share of projects with both announced_date and
     first_opposition_date.
  2. Precision symmetry: distribution of announced_precision.
  3. Clamp audit: raw negative spans (first opposition before announcement),
     which indicate announced-date errors; these are clamped to zero in the
     model and are emitted here as a date-recovery worklist.
  4. Precision-restricted comparison: medians and Mann-Whitney test on all
     precisions vs month-or-better only.

Writes data/feature_asymmetry_report.md. Read-only with respect to all
inputs; additive; not wired into CI (run manually after date recovery
passes, alongside outcome_model.py).

Usage: python feature_asymmetry_check.py
"""

from __future__ import annotations

import csv
import math
import os
import statistics as st
from collections import Counter
from datetime import date

ROOT = os.path.dirname(os.path.abspath(__file__))
LIFECYCLES_CSV = os.path.join(ROOT, "data", "project_lifecycles.csv")
FEATURES_CSV = os.path.join(ROOT, "data", "outcome_model_features.csv")
REPORT_MD = os.path.join(ROOT, "data", "feature_asymmetry_report.md")

GOOD_PRECISION = {"day", "month"}
ALL_PRECISION = {"day", "month", "year"}


def mann_whitney(x: list[float], y: list[float]) -> tuple[float, float]:
    """Two-sided Mann-Whitney via normal approximation with tie-averaged
    ranks. Returns (z, p). Adequate at these sample sizes; scipy is not a
    pipeline dependency."""
    vals = list(x) + list(y)
    order = sorted(range(len(vals)), key=lambda k: vals[k])
    ranks = [0.0] * len(vals)
    i = 0
    while i < len(order):
        j = i
        while j + 1 < len(order) and vals[order[j + 1]] == vals[order[i]]:
            j += 1
        avg = (i + j) / 2 + 1
        for k in range(i, j + 1):
            ranks[order[k]] = avg
        i = j + 1
    r1 = sum(ranks[: len(x)])
    u = r1 - len(x) * (len(x) + 1) / 2
    mu = len(x) * len(y) / 2
    sd = math.sqrt(len(x) * len(y) * (len(x) + len(y) + 1) / 12)
    if sd == 0:
        return 0.0, 1.0
    z = (u - mu) / sd
    p = 2 * (1 - 0.5 * (1 + math.erf(abs(z) / math.sqrt(2))))
    return z, p


def load() -> list[dict]:
    life = {r["project_id"]: r for r in csv.DictReader(open(LIFECYCLES_CSV, encoding="utf-8-sig"))}
    feat = list(csv.DictReader(open(FEATURES_CSV, encoding="utf-8-sig")))
    rows = []
    for f in feat:
        r = life.get(f["project_id"])
        if r is None:
            continue
        rows.append({
            "project_id": f["project_id"],
            "project_name": f.get("project_name", ""),
            "label_blocked": f["label_blocked"],
            "announced_date": (r.get("announced_date") or "").strip(),
            "first_opposition_date": (r.get("first_opposition_date") or "").strip(),
            "announced_precision": (r.get("announced_precision") or "missing").strip(),
        })
    return rows


def raw_span(row: dict) -> float | None:
    a, f = row["announced_date"], row["first_opposition_date"]
    if not a or not f:
        return None
    return (date.fromisoformat(f) - date.fromisoformat(a)).days


def arm_rows(rows: list[dict], label: str) -> list[dict]:
    return [r for r in rows if r["label_blocked"] == label]


def spans(rows: list[dict], precisions: set[str]) -> list[float]:
    out = []
    for r in rows:
        if r["announced_precision"] not in precisions:
            continue
        s = raw_span(r)
        if s is not None:
            out.append(max(s, 0))
    return out


def main() -> int:
    rows = load()
    blocked = arm_rows(rows, "1")
    notblocked = arm_rows(rows, "0")

    lines = []
    lines.append("# Feature Asymmetry Report: days_to_first_opposition")
    lines.append("")
    lines.append("Auto-generated by feature_asymmetry_check.py. Re-run after date "
                 "recovery passes.")
    lines.append("")

    # 1. Coverage
    lines.append("## Coverage symmetry")
    lines.append("")
    lines.append("| Arm | n | both dates present | share |")
    lines.append("|---|---|---|---|")
    for name, arm in (("blocked_confirmed", blocked), ("not blocked", notblocked)):
        have = [r for r in arm if raw_span(r) is not None]
        share = 100.0 * len(have) / len(arm) if arm else 0.0
        lines.append(f"| {name} | {len(arm)} | {len(have)} | {share:.0f}% |")
    lines.append("")

    # 2. Precision
    lines.append("## Announced-date precision by arm")
    lines.append("")
    lines.append("| Arm | day | month | year | missing |")
    lines.append("|---|---|---|---|---|")
    for name, arm in (("blocked_confirmed", blocked), ("not blocked", notblocked)):
        c = Counter(r["announced_precision"] for r in arm)
        lines.append(f"| {name} | {c.get('day', 0)} | {c.get('month', 0)} | "
                     f"{c.get('year', 0)} | {c.get('missing', 0)} |")
    lines.append("")
    lines.append("Year-precision announced dates inflate the computed span by up to "
                 "roughly a year. An imbalance in year-precision across arms can "
                 "create or exaggerate an arrival-speed difference; the restricted "
                 "comparison below controls for this.")
    lines.append("")

    # 3. Clamp audit / date-recovery worklist
    lines.append("## Announced-date error worklist (raw negative spans)")
    lines.append("")
    lines.append("First opposition recorded before the announced date. The model "
                 "clamps these to zero; the underlying announced dates need "
                 "correction via date recovery.")
    lines.append("")
    lines.append("| project_id | project_name | arm | raw span (days) | announced precision |")
    lines.append("|---|---|---|---|---|")
    n_neg = 0
    for r in rows:
        s = raw_span(r)
        if s is not None and s < 0:
            n_neg += 1
            armname = "blocked_confirmed" if r["label_blocked"] == "1" else "not blocked"
            lines.append(f"| {r['project_id']} | {r['project_name']} | {armname} | "
                         f"{s:.0f} | {r['announced_precision']} |")
    if n_neg == 0:
        lines.append("| (none) | | | | |")
    lines.append("")

    # 4. Restricted comparison
    lines.append("## Arrival-speed comparison")
    lines.append("")
    lines.append("| Restriction | blocked n | blocked median (d) | not-blocked n | "
                 "not-blocked median (d) | Mann-Whitney z | p |")
    lines.append("|---|---|---|---|---|---|---|")
    for name, precs in (("all precisions", ALL_PRECISION),
                        ("month-or-better", GOOD_PRECISION)):
        b = spans(blocked, precs)
        nb = spans(notblocked, precs)
        if not b or not nb:
            lines.append(f"| {name} | {len(b)} | | {len(nb)} | | | |")
            continue
        z, p = mann_whitney(b, nb)
        lines.append(f"| {name} | {len(b)} | {st.median(b):.0f} | {len(nb)} | "
                     f"{st.median(nb):.0f} | {z:.2f} | {p:.3f} |")
    lines.append("")
    lines.append("Interpretation rule: the feature may be described in reports as "
                 "directionally associated with blocking only if the direction "
                 "holds under the month-or-better restriction. Statistical "
                 "significance language requires p below 0.05 in the restricted "
                 "comparison; otherwise reports say the association is "
                 "suggestive and underpowered at current sample size.")
    lines.append("")

    os.makedirs(os.path.dirname(REPORT_MD), exist_ok=True)
    with open(REPORT_MD, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines) + "\n")
    print(f"wrote {os.path.relpath(REPORT_MD, ROOT)}: "
          f"{len(blocked)} blocked / {len(notblocked)} not blocked, "
          f"{n_neg} announced-date errors flagged")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
