#!/usr/bin/env python3
"""
resolve_generated_conflicts.py

Resolves merge conflicts in generated artifacts by regenerating them, and
refuses to touch anything else.

Why this exists
---------------
Every derived artifact in this repository is both regenerated by a module and
committed, because the HTML surfaces fetch them from the repo at runtime.
Those two facts together produce a standing tax: two branches that each ran the
pipeline rewrote the same derived files, so any pair of active branches
conflicted on them within a run or two, whatever their actual changes were. A
single pull request in 2026-09 hit the same five files across four separate
merge rounds and spent more effort on them than on its own diff.

Resolving one by hand is not just tedious, it is wrong. Picking a side leaves
an artifact that matches neither branch's inputs, and editing the conflict
markers out by hand produces a file no run would ever produce. The only correct
resolution for a derived file is to take either side, then regenerate it from
the merged inputs. That is mechanical, which is what this module automates.

`.gitattributes` (generated by layer_audit.py --write-gitattributes) marks
these paths `-merge`, so git leaves OUR version intact and flags the conflict
rather than writing <<<<<<< markers into a .json or .csv a page fetches. This
script then regenerates.

What it will not do
-------------------
It resolves ONLY paths that layer_audit.py reports as regenerable. A conflict
in a source of record, an append-only file, or any hand-maintained file is left
untouched and reported, because those need a person. Files declared
not_regenerable in configs/layers.json are never resolved here.

Usage
  python scripts/resolve_generated_conflicts.py            resolve and regenerate
  python scripts/resolve_generated_conflicts.py --dry-run  report only
  python scripts/resolve_generated_conflicts.py --selftest
"""

from __future__ import annotations

import argparse
import os
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, ROOT)

# Modules to re-run, in dependency order, to rebuild the derived layer. Each is
# cheap, offline and idempotent. Ordering matters where one reads another's
# output: the county aggregate is rebuilt before anything that reads it.
REGENERATORS = [
    ("layer_audit.py", []),
    ("visibility_audit.py", []),
    ("restriction_evidence.py", []),
]


def git(*args: str) -> str:
    return subprocess.run(["git", "-C", ROOT, *args],
                          capture_output=True, text=True).stdout.strip()


def conflicted_paths() -> list[str]:
    """Paths git currently reports as unmerged."""
    out = git("diff", "--name-only", "--diff-filter=U")
    return [p for p in out.splitlines() if p.strip()]


def classify(paths: list[str]) -> tuple[list[str], list[str]]:
    """Split conflicts into (regenerable, needs_a_person)."""
    try:
        import layer_audit
        generated = set(layer_audit.generated_paths(ROOT))
    except Exception as exc:  # pragma: no cover - defensive
        print(f"could not load the write map: {exc}", file=sys.stderr)
        return [], list(paths)
    regen = [p for p in paths if p in generated]
    manual = [p for p in paths if p not in generated]
    return regen, manual


def resolve(regen: list[str], dry_run: bool) -> int:
    if not regen:
        return 0
    for p in regen:
        print(f"  take ours + regenerate: {p}")
        if not dry_run:
            # Take our side so the file holds valid content while the
            # regenerators run. They overwrite it immediately after.
            subprocess.run(["git", "-C", ROOT, "checkout", "--ours", "--", p],
                           capture_output=True, text=True)
    if dry_run:
        return len(regen)

    print("\nregenerating:")
    for module, extra in REGENERATORS:
        path = os.path.join(ROOT, module)
        if not os.path.exists(path):
            continue
        r = subprocess.run([sys.executable, path, *extra],
                           cwd=ROOT, capture_output=True, text=True)
        state = "ok" if r.returncode == 0 else f"exit {r.returncode}"
        print(f"  {module}: {state}")

    for p in regen:
        subprocess.run(["git", "-C", ROOT, "add", "--", p],
                       capture_output=True, text=True)
    return len(regen)


def selftest() -> int:
    failures = []

    def ck(name, got, want):
        if got != want:
            failures.append(f"{name}: expected {want!r}, got {got!r}")

    import layer_audit
    generated = set(layer_audit.generated_paths(ROOT))

    # A derived artifact is resolvable here.
    ck("a derived artifact classifies as regenerable",
       "data/layer_audit_summary.json" in generated, True)

    # Sources of record and append-only files never are.
    for p in ("master_opposition.csv",
              "data/external_restriction_census.csv",
              "data/restriction_evidence_history.csv",
              "data/census_promotion_report.csv"):
        ck(f"{p} is never auto-resolved", p in generated, False)

    # classify() must route them accordingly rather than crashing.
    regen, manual = classify(["data/layer_audit_summary.json",
                              "master_opposition.csv",
                              "some/unknown/path.txt"])
    ck("derived routes to regenerable", regen, ["data/layer_audit_summary.json"])
    ck("source of record routes to a person",
       "master_opposition.csv" in manual, True)
    ck("an unknown path routes to a person",
       "some/unknown/path.txt" in manual, True)

    # Nothing conflicted means nothing to do, and that is success not failure.
    ck("empty input resolves to zero", resolve([], dry_run=True), 0)

    if failures:
        print("SELFTEST FAIL")
        for f in failures:
            print("  " + f)
        return 1
    print("resolve_generated_conflicts.py selftest: OK")
    return 0


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--dry-run", action="store_true")
    ap.add_argument("--selftest", action="store_true")
    args = ap.parse_args()

    if args.selftest:
        return selftest()

    paths = conflicted_paths()
    if not paths:
        print("no conflicted paths")
        return 0

    regen, manual = classify(paths)
    print(f"{len(paths)} conflicted path(s): {len(regen)} regenerable, "
          f"{len(manual)} need a person\n")

    if regen:
        resolve(regen, args.dry_run)

    if manual:
        print("\nleft for a person (source of record, append-only, or "
              "hand-maintained):")
        for p in manual:
            print(f"  {p}")
        print("\nResolve those by hand, then commit. This module will not "
              "touch them.")
        return 1

    print(f"\nresolved {len(regen)} generated path(s). Review, then commit.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
